spring :
  mail:
    host: smtp.gmail.com
    port: 587
    username: dlfwnd97@gmail.com
    password: thdus0205#
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
