spring :
  datasource:
    url: jdbc:mysql://13.209.94.31:3306/myhome?characterEncoding=utf8
    username: bdgom97
    password: dlf123
    driverClassName: com.mysql.cj.jdbc.Driver
  # 개발용 h2 db
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

#      mysql => 52.79.66.187:3306  aws mysql.