
server :
  port : 5050
spring :
  jpa:
    hibernate:
      ddl-auto: update
      hbm2ddl: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        dialect : org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart :
      max-file-size : 2GB
      max-request-size: 2GB

logging.level:
  org.hibernate.SQL: debug

---
spring :
  profiles :
    include : "db"
---
spring :
  profiles :
    include : "aws"
---
spring :
  profiles :
    include : "aws_key"
---
spring :
  profiles :
    include : "mail"
