
server :
  port : 5050
spring :
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
#        dialect : org.hibernate.dialect.MySQLInnoDBDialect
        dialect : org.hibernate.dialect.MySQL5Dialect
#        database-platform : org.hibernate.dialect.Oracle10gDialect
  servlet:
    multipart :
      max-file-size : 2GB
      max-request-size: 2GB

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
---
spring :
  profiles :
    include : "db"
---
spring :
  profiles :
    include : "aws"
---
spring :
  profiles :
    include : "aws_key"
---
spring :
  profiles :
    include : "mail"
